SELECT CUSTOMER_ID,FIRST_NAME,LAST_NAME,CITY,
FROM CUSTOMERS;

SELECT CUSTOMER_ID,FIRST_NAME + ' ' +LAST_NAME AS 'CUSTOMER NAME',CITY
FROM CUSTOMERS;

SELECT PRODUCT_ID,PRODUCT_NAME,LIST_PRICE,
FROM PRODUCTS,


SELECT * FROM CUSTOMERS;